### ISSUE TITLE
NPE with some modded items

### ISSUE THREAD

**Issue by Sirse** [MinecraftWars/Gringotts#134]
Hi. I modify your plugin to get stacktrace and hope you will fix that NPE in next releases:

[Server thread/ERROR] [org.gestern.gringotts.Gringotts/]: [Gringotts] Encountered an error parsing currency. Please check your Gringotts configuration. 
java.lang.NullPointerException
	at org.gestern.gringotts.Configuration.unitName(Configuration.java:272)
	at org.gestern.gringotts.Configuration.parseCurrency(Configuration.java:184)
	at org.gestern.gringotts.Configuration.readConfig(Configuration.java:117)
	at org.gestern.gringotts.Gringotts.reloadConfig(Gringotts.java:178)
	at org.gestern.gringotts.Gringotts.onEnable(Gringotts.java:66)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
	at net.minecraft.world.World.<init>(World.java:360)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MarkehMe** [comment]
What was the issue before you modified the plugin?

**Comment by Sirse** [comment]
Plugin just don't load on startup. If i fill unit-name section in config manually, all works fine. You should add nullcheck to Configuration.unitName method.

**Comment by jastice** [comment]
Is this still an issue? In that case, please paste your complete Gringotts config in code format.

**Comment by jastice** [comment]
Assumed obsolete, closing.
