### ISSUE TITLE
org.apache.commons.lang.UnhandledException: Plugin Gringotts v2.7 generated an exception while executing task 2

### ISSUE THREAD

**Issue by PureTryOut** [MinecraftWars/Gringotts#139]
Running Spigot for 1.9, which is probably the problem.
Gringotts loads and runs fine, but after startup is done it reports this error:
```
[15:51:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin Gringotts v2.7 generated an exception while executing task 2
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.gestern.mcstats.MetricsLite.postPlugin(MetricsLite.java:287)
        at org.gestern.mcstats.MetricsLite.access$200(MetricsLite.java:53)
        at org.gestern.mcstats.MetricsLite$1.run(MetricsLite.java:175)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

Not a deal breaker since it works fine, but it does spam the console.

**Comment by jaime29010** [comment]
You can download a version fixed for 1.9 [here](https://github.com/jaime29010/Gringotts/releases/tag/2.7-spigot1.9fix)

**Comment by PureTryOut** [comment]
Thanks, that works!

**Comment by jastice** [comment]
Official update now also released: http://dev.bukkit.org/bukkit-plugins/gringotts/files/34-gringotts-v2-8/
