### ISSUE TITLE
Vault plugin required?

### ISSUE THREAD

**Issue by games647** [MinecraftWars/Gringotts#165]
`java.lang.NoClassDefFoundError: net/milkbowl/vault/item/Items
	at org.gestern.gringotts.Configuration.unitName(Configuration.java:112) ~[?:?]
	at org.gestern.gringotts.Configuration.parseCurrency(Configuration.java:242) ~[?:?]
	at org.gestern.gringotts.Configuration.readConfig(Configuration.java:164) ~[?:?]
	at org.gestern.gringotts.Gringotts.reloadConfig(Gringotts.java:224) ~[?:?]
	at org.gestern.gringotts.Gringotts.onEnable(Gringotts.java:99) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-"d934dcc1"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-"d934dcc1"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-"d934dcc1"]
`
According to your plugin.yml the vault plugin isn't required, but if Vault isn't installed on the server this error pops up.

**Comment by MarkehMe** [comment]
Install Vault

**Comment by jastice** [comment]
Technically a bug because it shouldn't be required, but someone would want to fix it

**Comment by MarkehMe** [comment]
Maybe shade/shadow net.milkbowl.vault.item.* into the jar?

**Comment by bundabrg** [comment]
Vault no longer handles items as per #182
