### ISSUE TITLE
Towny vaults not being created.

### ISSUE THREAD

**Issue by Zanzoman** [MinecraftWars/Gringotts#175]
Not sure if its completely due to Gringotts or Towny, but if i create a vault, with the sign on it saying [town vault], it works for some people and not for others. Any help?
![bad](https://user-images.githubusercontent.com/36989871/39393155-07ea58ca-4b01-11e8-8708-3b8e87dd4b78.png)

**Comment by Heacien** [comment]
Same with v2.10.1

 `[21:25:46 ERROR]: Could not pass event PlayerVaultCreationEvent to Gringotts v2.10.1-SNAPSHOT`

### Server details:
- Spigot (V 1.12.2)
- Towny (V 0.93.0.0)
- Multiverse Inventories (V 2.5.0-SNAPSHOT)

### Full error message:

	[21:25:46 ERROR]: Could not pass event PlayerVaultCreationEvent to Gringotts v2.10.1-SNAPSHOT
	org.bukkit.event.EventException: null
			at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.gestern.gringotts.event.AccountListener.createVault(AccountListener.java:52) [Gringotts-2.10.1-SNAPSHOT.jar:?]
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
			at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2136) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:44) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
			at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
			at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
	Caused by: javax.persistence.PersistenceException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: gringotts_accountchest.account)
			at com.avaje.ebeaninternal.server.persist.ExeUpdateSql.execute(ExeUpdateSql.java:95) ~[?:?]
			at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeSqlUpdate(DefaultPersistExecute.java:144) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeNow(PersistRequestUpdateSql.java:63) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequest.executeStatement(PersistRequest.java:93) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeOrQueue(PersistRequestUpdateSql.java:68) ~[?:?]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.executeSqlUpdate(DefaultPersister.java:166) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1947) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1954) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultSqlUpdate.execute(DefaultSqlUpdate.java:167) ~[?:?]
			at org.gestern.gringotts.data.EBeanDAO.storeAccountChest(EBeanDAO.java:63) ~[?:?]
			at org.gestern.gringotts.Accounting.addChest(Accounting.java:79) ~[?:?]
			at org.gestern.gringotts.event.VaultCreator.registerVault(VaultCreator.java:45) ~[?:?]
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
			at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			... 24 more
	Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: gringotts_accountchest.account)
			at org.sqlite.core.DB.newSQLException(DB.java:909) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.sqlite.core.DB.newSQLException(DB.java:921) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.sqlite.core.DB.execute(DB.java:825) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.sqlite.core.DB.executeUpdate(DB.java:863) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[?:?]
			at com.avaje.ebeaninternal.server.persist.ExeUpdateSql.execute(ExeUpdateSql.java:87) ~[?:?]
			at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeSqlUpdate(DefaultPersistExecute.java:144) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeNow(PersistRequestUpdateSql.java:63) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequest.executeStatement(PersistRequest.java:93) ~[?:?]
			at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeOrQueue(PersistRequestUpdateSql.java:68) ~[?:?]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.executeSqlUpdate(DefaultPersister.java:166) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1947) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1954) ~[?:?]
			at com.avaje.ebeaninternal.server.core.DefaultSqlUpdate.execute(DefaultSqlUpdate.java:167) ~[?:?]
			at org.gestern.gringotts.data.EBeanDAO.storeAccountChest(EBeanDAO.java:63) ~[?:?]
			at org.gestern.gringotts.Accounting.addChest(Accounting.java:79) ~[?:?]
			at org.gestern.gringotts.event.VaultCreator.registerVault(VaultCreator.java:45) ~[?:?]
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
			at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
			at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
			... 24 more

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
