### ISSUE TITLE
WorldGuard API changes cause Exceptions

### ISSUE THREAD

**Issue by bundabrg** [MinecraftWars/Gringotts#186]
WorldGuard have broken the API again and the following exceptions are seen (in my case when I type `/moneyadmin b <invalid username>':

```
00:42:59 [INFO] [dreamland] [00:42:59 INFO]: Bundie issued server command: /moneyadmin b bbb
00:42:59 [INFO] [dreamland] [00:42:59 ERROR]: null
00:42:59 [INFO] [dreamland] org.bukkit.command.CommandException: Unhandled exception executing command 'moneyadmin' in plugin Gringotts v2.10.1-SNAPSHOT
00:42:59 [INFO] [dreamland]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1757) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1561) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
00:42:59 [INFO] [dreamland]     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
00:42:59 [INFO] [dreamland] Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
00:42:59 [INFO] [dreamland]     at org.gestern.gringotts.dependency.WorldGuardHandler.getAccountHolder(WorldGuardHandler.java:62) ~[?:?]
00:42:59 [INFO] [dreamland]     at org.gestern.gringotts.dependency.WorldGuardHandler.getAccountHolder(WorldGuardHandler.java:23) ~[?:?]
00:42:59 [INFO] [dreamland]     at org.gestern.gringotts.accountholder.AccountHolderFactory.get(AccountHolderFactory.java:35) ~[?:?]
00:42:59 [INFO] [dreamland]     at org.gestern.gringotts.api.impl.GringottsEco.account(GringottsEco.java:31) ~[?:?]
00:42:59 [INFO] [dreamland]     at org.gestern.gringotts.Commands$Moneyadmin.onCommand(Commands.java:213) ~[?:?]
00:42:59 [INFO] [dreamland]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-402]
00:42:59 [INFO] [dreamland]     ... 15 more
```

I'll see if I can send a PR to fix.

**Comment by bundabrg** [comment]
Support for wg 7.0.0 added.
