### ISSUE TITLE
Can't create a town with Towny, have both Vault, Gringotts and Towny

### ISSUE THREAD

**Issue by Onionus007** [MinecraftWars/Gringotts#214]
`[21:25:18] [Server thread/INFO]: Onionus issued server command: /town new Tokio
[21:25:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'town' in plugin Towny v0.95.2.17
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: accountHolderFactory
        at net.milkbowl.vault.economy.plugins.Economy_Gringotts.hasAccount(Economy_Gringotts.java:126) ~[?:?]
        at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:257) ~[?:?]
        at com.palmergames.bukkit.towny.TownyEconomyHandler.hasEnough(TownyEconomyHandler.java:280) ~[?:?]
        at com.palmergames.bukkit.towny.object.EconomyAccount.canPayFromHoldings(EconomyAccount.java:189) ~[?:?]
        at com.palmergames.bukkit.towny.object.EconomyAccount._pay(EconomyAccount.java:63) ~[?:?]
        at com.palmergames.bukkit.towny.object.EconomyAccount.pay(EconomyAccount.java:53) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownCommand.newTown(TownCommand.java:2305) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:397) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:314) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigotmc-1.15.2.jar:git-Spigot-800b93f-8160e29]
        ... 17 more`

**Comment by Darklom** [comment]
My players cannot access the /town command either

Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'towny:town' in plugin Towny v0.96.0.0

**Comment by nikosgram** [comment]
Hello @Darklom, 

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-ref98c00

Try this pre-release version. Please remember, this is a pre-release version, only for testing purposes.

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
