### ISSUE TITLE
SignBank and Gringotts

### ISSUE THREAD

**Issue by diannetea** [MinecraftWars/Gringotts#58]
2013-01-14 17:18:02 [SEVERE] Could not pass event AsyncPlayerChatEvent to Sign Bank v2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:24)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
	at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:913)
	at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:852)
	at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
	at net.minecraft.server.v1_4_6.NetworkManager.i(NetworkManager.java:208)
	at net.minecraft.server.v1_4_6.NetworkManager.c(NetworkManager.java:344)
	at net.minecraft.server.v1_4_6.NetworkReaderThread.run(SourceFile:93)
Caused by: org.gestern.gringotts.GringottsStorageException: Failed to get account for owner: PlayerAccountHolder(diannetea)
	at org.gestern.gringotts.DAO.getAccount(DAO.java:268)
	at org.gestern.gringotts.Accounting.getAccount(Accounting.java:26)
	at org.gestern.gringotts.api.VaultEconomy.depositPlayer(VaultEconomy.java:130)
	at com.brandenBoegh.SignBank.SignBankListener.makeTransaction(SignBankListener.java:108)
	at com.brandenBoegh.SignBank.SignBankListener.onEnterAmount(SignBankListener.java:91)
	at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
	... 10 more
Caused by: java.sql.SQLNonTransientConnectionException: Connection closed by unknown interrupt.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.closeOnTransactionError(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.next(Unknown Source)
	at org.gestern.gringotts.DAO.getAccount(DAO.java:259)
	... 18 more
Caused by: java.sql.SQLException: Connection closed by unknown interrupt.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 28 more
Caused by: ERROR 08000: Connection closed by unknown interrupt.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.util.InterruptStatus.setInterrupted(Unknown Source)
	at org.apache.derby.iapi.util.InterruptStatus.throwIf(Unknown Source)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.checkCancellationFlag(Unknown Source)
	at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.IndexRowToBaseRowResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)
	... 21 more

**Comment by jastice** [comment]
Is this still an issue for you?

**Comment by jastice** [comment]
Closing due to relative obscurity. Let me know if the error persists and it's even still relevant.
